name: 💡 Feature
description: Request for a new feature
title: "[FEATURE] <title>"
labels: ["type: feature"]
body:
  - type: textarea
    attributes:
      label: Description
      description: A description of the feature.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Task List
      description: Describe the steps to fulfill the feature.
      value: |
        - [ ] My First Task
    validations:
      required: true